In [1]:
import numpy as np
import pandas as pd


In [6]:
df = pd.read_csv('/kaggle/input/spotify-song-performance-dataset/spotify_data.csv')


In [8]:
df.isnull().sum()

Songs & Artist    0
Streams           0
Daily             2
dtype: int64

In [10]:
 df=df.fillna("0")

In [11]:
df.isnull().sum()

Songs & Artist    0
Streams           0
Daily             0
dtype: int64

In [14]:
df=pd.get_dummies(df).astype(int)

In [15]:
df

Streams  \
0     4463658617   
1     4018102402   
2     3588673578   
3     3544187311   
4     3518744128   
...          ...   
2495   505592800   
2496   505511969   
2497   505386377   
2498   505309100   
2499   505249124   

      Songs & Artist_$uicideboy$ - ...And to Those I Love, Thanks for Sticking Around  \
0                                                     0                                 
1                                                     0                                 
2                                                     0                                 
3                                                     0                                 
4                                                     0                                 
...                                                 ...                                 
2495                                                  0                                 
2496                                                  0                                 
2497                                                  0                                 
2498                                                  0                                 
2499                                                  0                                 

      Songs & Artist_$uicideboy$ - Kill Yourself (Part III)  \
0                                                     0       
1                                                     0       
2                                                     0       
3                                                     0       
4                                                     0       
...                                                 ...       
2495                                                  0       
2496                                                  0       
2497                                                  0       
2498                                                  0       
2499                                                  0       

      Songs & Artist_$uicideboy$ - Paris  Songs & Artist_*NSYNC - Bye Bye Bye  \
0                                      0                                    0   
1                                      0                                    0   
2                                      0                                    0   
3                                      0                                    0   
4                                      0                                    0   
...                                  ...                                  ...   
2495                                   0                                    0   
2496                                   0                                    0   
2497                                   0                                    0   
2498                                   0                                    0   
2499                                   0                                    0   

      Songs & Artist_21 Savage - Bank Account  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   
...                                       ...   
2495                                        0   
2496                                        0   
2497                                        0   
2498                                        0   
2499                                        0   

      Songs & Artist_21 Savage - Glock In My Lap  \
0                                              0   
1                                              0   
2                                              0   
3                                              0   
4                                              0   
...                                          ...   
2495            

# # AutoEncoder

In [21]:
from keras.layers import Dense,Flatten,LSTM,Dropout,SimpleRNN,GRU,Input,BatchNormalization,ReLU
from keras.models import Model
from keras.initializers import HeNormal
from keras.regularizers import l2
from keras.callbacks import EarlyStopping

In [23]:
early_stopping=EarlyStopping(
monitor='val_loss',
patience=5,
verbose=1)

In [26]:
train_df=df.values
train_df=train_df.reshape(train_df.shape[0],1,train_df.shape[1])
train_df.shape

(2500, 1, 4970)

In [22]:
inputs=Input(shape=(1,4970))
L=LSTM(32,activation="relu",return_sequences=True,kernel_initializer=HeNormal(),kernel_regularizer=l2(0.01))(inputs)
L=Dropout(0.5)(L)
L=BatchNormalization()(L)
L=LSTM(64,return_sequences=True,kernel_initializer=HeNormal(),kernel_regularizer=l2(0.01))(L)
L=ReLU()(L)
L=Dropout(0.5)(L)
L=BatchNormalization()(L)
L=LSTM(128,return_sequences=True,kernel_initializer=HeNormal(),kernel_regularizer=l2(0.01))(L)
L=ReLU()(L)
L=Dropout(0.5)(L)
L=BatchNormalization()(L)

L=LSTM(256,return_sequences=True,kernel_initializer=HeNormal(),kernel_regularizer=l2(0.01))(L)
L=ReLU()(L)
L=Dropout(0.5)(L)
L=BatchNormalization()(L)

L=LSTM(128,return_sequences=True,kernel_initializer=HeNormal(),kernel_regularizer=l2(0.01))(L)
L=ReLU()(L)
L=Dropout(0.5)(L)
L=BatchNormalization()(L)

L=LSTM(64,return_sequences=True,kernel_initializer=HeNormal(),kernel_regularizer=l2(0.01))(L)
L=ReLU()(L)
L=Dropout(0.5)(L)
L=BatchNormalization()(L)
L=LSTM(32,return_sequences=True,kernel_initializer=HeNormal(),kernel_regularizer=l2(0.01))(L)
L=ReLU()(L)
L=Dropout(0.5)(L)
L=BatchNormalization()(L)
outputs=LSTM(1,activation="sigmoid",return_sequences=True)(L)
model=Model(inputs,outputs)
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=["accuracy"])
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)      │ (None, 1, 4970)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 1, 32)          │       640,384 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 1, 32)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 1, 32)          │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 1, 64)          │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu (ReLU)                    │ (None, 1, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 1, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 1, 64)          │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ (None, 1, 128)         │        98,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_1 (ReLU)                  │ (None, 1, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 1, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 1, 128)         │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_9 (LSTM)                   │ (None, 1, 256)         │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_2 (ReLU)                  │ (None, 1, 256)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 1, 256)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 1, 256)         │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_10 (LSTM)                  │ (None, 1, 128)         │       197,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_3 (ReLU)                  │ (None, 1, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 1, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 1, 128)         │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_11 (LSTM)                  │ (None, 1, 64)          │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ re_lu_4 (ReLU)                  │ (None, 1, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼─────────────

 Total params: 100,879,672 (384.83 MB)

 Trainable params: 100,878,264 (384.82 MB)

 Non-trainable params: 1,408 (5.50 KB)

In [27]:
model.fit(train_df,train_df,epochs=10,batch_size=32,validation_split=0.2,callbacks=[early_stopping])

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 105s 1s/step - accuracy: 0.1316 - loss: 1855352.6250 - val_accuracy: 1.0000 - val_loss: 413918.2812
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.5384 - loss: 1321118.1250 - val_accuracy: 1.0000 - val_loss: 306013.8750
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.6998 - loss: 1071997.3750 - val_accuracy: 1.0000 - val_loss: 224132.7031
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.7972 - loss: 821798.0000 - val_accuracy: 1.0000 - val_loss: 158098.2969
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 143s 1s/step - accuracy: 0.8506 - loss: 675926.7500 - val_accuracy: 1.0000 - val_loss: 103068.1250
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 142s 1s/step - accuracy: 0.8809 - loss: 508254.2500 - val_accuracy: 1.0000 - val_loss: 53171.9883
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 87s 1s/step - accuracy: 0.9250 - loss: 390391.6250 - val_accuracy: 1.0000 - val_loss: 20417.9434
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 142s 1

In [34]:
from sklearn.metrics import *
test_data=train_df[100:200]
prediction_test=model.predict(test_data)
   
binary_prediction=(prediction_test>0.5).astype(int)
prediction=model.predict(train_df)
reconstruction_normal=np.mean(np.square(train_df-prediction),axis=1)
reconstruction_test=np.mean(np.square(test_data-prediction_test),axis=1)

threshold=np.mean(reconstruction_normal)+2*np.std(reconstruction_normal)
label=np.where(reconstruction_test>threshold,0,1)
print(label)
test_data=test_data.flatten()
binary_prediction=binary_prediction.flatten()


print(accuracy_score(test_data,binary_prediction))

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
79/79 ━━━━━━━━━━━━━━━━━━━━ 7s 92ms/step
[[0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]]
0.9993963782696177
