In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor,BaggingRegressor
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier,BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.naive_bayes import BernoulliNB

In [21]:
df=pd.read_csv("/kaggle/input/drosophila-melanogaster-genome/ensembl-gtp.csv")

In [22]:
df.isnull().sum()

gene             0
transcript       0
protein       4363
dtype: int64

In [23]:
df=df.dropna(how="any",axis=0)
df=df.iloc[0:500,:]
df.isnull().sum()

gene          0
transcript    0
protein       0
dtype: int64

In [24]:
df.nunique()

gene          201
transcript    500
protein       500
dtype: int64

In [25]:
label_encoder=LabelEncoder()
for i in df.columns:
    df[i]=label_encoder.fit_transform(df[i])
df

gene  transcript  protein
1     200         498      498
4     199         497      497
7     171         276      277
8      10         254      255
9     166         295      295
..    ...         ...      ...
555   128         464      464
556   128         465      465
557   128          29       29
558   129         287      288
559   129          30       30

[500 rows x 3 columns]

In [26]:
X=df.drop(columns=["protein"])
Y=df["protein"]


In [27]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [28]:
def model_train(X_train,X_test,Y_train,Y_test):
    for i in [RandomForestRegressor(),GradientBoostingRegressor(),AdaBoostRegressor(),BaggingRegressor(),KNeighborsRegressor(),DecisionTreeRegressor()]:
        random_reg=i
        random_reg.fit(X_train,Y_train)
        print(f"The Accuracy score {i} is :",random_reg.score(X_test,Y_test))
model_train(X_train,X_test,Y_train,Y_test)

The Accuracy score RandomForestRegressor() is : 0.995432631800281
The Accuracy score GradientBoostingRegressor() is : 0.991356724275334
The Accuracy score AdaBoostRegressor() is : 0.9826065947816564
The Accuracy score BaggingRegressor() is : 0.9923524321703509
The Accuracy score KNeighborsRegressor() is : 0.9875197997269003
The Accuracy score DecisionTreeRegressor() is : 0.9982812530921612


In [39]:
df2=pd.read_csv("/kaggle/input/drosophila-melanogaster-genome/genes-refseq.csv")

In [40]:
df2=df2.iloc[:500,:]
df2.isnull().sum()

bin             0
name            0
chrom           0
strand          0
txStart         0
txEnd           0
cdsStart        0
cdsEnd          0
exonCount       0
exonStarts      0
exonEnds        0
score           0
name2           0
cdsStartStat    0
csdEndStat      0
exonFrames      0
dtype: int64

In [41]:
df2

bin          name  chrom strand   txStart     txEnd  cdsStart    cdsEnd  \
0    812  NM_001170300  chr3R      +  29836567  29837447  29836625  29837342   
1    802  NM_001170290  chr3R      -  28520664  28540324  28521128  28539941   
2    802  NM_001170289  chr3R      -  28520664  28540324  28521128  28539941   
3    713  NM_001103535   chrX      +  16811698  16826494  16812002  16826138   
4    713  NM_001103536   chrX      -  16826680  16835520  16827398  16828074   
..   ...           ...    ...    ...       ...       ...       ...       ...   
495  791  NM_001104470  chr3R      -  27057907  27063778  27059066  27063391   
496  786  NM_001104468  chr3R      -  26425289  26425781  26425322  26425508   
497  786  NM_001104467  chr3R      -  26401908  26403656  26401908  26403656   
498   97  NM_001104466  chr3R      -  26076591  26098711  26077466  26098145   
499   97  NM_001104465  chr3R      -  26076591  26098052  26077221  26096529   

     exonCount                                         exonStarts  \
0            3                        29836567,29836912,29837317,   
1           17  28520664,28521356,28521541,28521814,28522481,2...   
2           12  28520664,28521356,28521541,28522481,28522694,2...   
3            7  16811698,16822556,16823102,16823856,16824358,1...   
4            3                        16826680,16827675,16834611,   
..         ...                                                ...   
495          8  27057907,27058712,27059364,27060257,27060602,2...   
496          2                                 26425289,26425745,   
497          5      26401908,26402207,26403003,26403239,26403528,   
498         10  26076591,26078807,26079366,26079551,26081891,2...   
499         11  26076591,26077471,26078807,26079366,26079551,2...   

                                              exonEnds  score    name2  \
0                          29836832,29837262,29837447,      0  CG15510   
1    28521298,28521473,28521700,28522231,28522632,2...      0      Ppn   
2    28521298,28521473,28521700,28522632,28523260,2...      0      Ppn   
3    16812061,16822772,16823206,16824118,16824772,1...      0   CG4829   
4                          16827605,16828075,16835520,      0  CG13004   
..                                                 ...    ...      ...   
495  27058582,27059119,27060196,27060540,27061176,2...      0     Nep5   
496                                 26425520,26425781,      0  CG34291   
497      26402137,26402896,26403184,26403464,26403656,      0    ppk15   
498  26078682,26078961,26079473,26079736,26082191,2...      0     dysf   
499  26077235,26078682,26078961,26079473,26079736,2...      0     dysf   

    cdsStartStat csdEndStat                          exonFrames  
0           cmpl       cmpl                              0,0,2,  
1           cmpl       cmpl  1,1,1,1,0,1,1,1,0,1,1,0,2,2,0,2,0,  
2           cmpl       cmpl            1,1,1,0,1,1,0,2,2,0,2,0,  
3           cmpl       cmpl                      0,2,2,1,2,2,2,  
4           cmpl       cmpl                             0,0,-1,  
..           ...        ...                                 ...  
495         cmpl       cmpl                   -1,1,0,2,1,2,1,0,  
496         cmpl       cmpl                               0,-1,  
497         cmpl       cmpl                          2,0,2,2,0,  
498         cmpl       cmpl                2,1,2,0,0,0,1,2,1,0,  
499         cmpl       cmpl             1,2,1,2,0,0,0,1,2,0,-1,  

[500 rows x 16 columns]

In [42]:
df2["exonFrames"]=df2["exonFrames"].apply(lambda x:[int(i) for i in x.split(',') if i])
df2["exonEnds"]=df2["exonEnds"].apply(lambda x:[int(i) for i in x.split(',') if i])
df2["exonStarts"]=df2["exonStarts"].apply(lambda x:[int(i) for i in x.split(',') if i])

In [43]:
chrom_encoder=LabelEncoder()
df2["chrom"]=chrom_encoder.fit_transform(df2["chrom"])
df2["strand"]=chrom_encoder.fit_transform(df2["strand"])
df2["name"]=chrom_encoder.fit_transform(df2["name"])
df2["name2"]=chrom_encoder.fit_transform(df2["name2"])
df2["cdsStartStat"]=chrom_encoder.fit_transform(df2["cdsStartStat"])
df2["csdEndStat"]=chrom_encoder.fit_transform(df2["csdEndStat"])

In [44]:
df2

bin  name  chrom  strand   txStart     txEnd  cdsStart    cdsEnd  \
0    812   315      2       0  29836567  29837447  29836625  29837342   
1    802   313      2       1  28520664  28540324  28521128  28539941   
2    802   312      2       1  28520664  28540324  28521128  28539941   
3    713     1      3       0  16811698  16826494  16812002  16826138   
4    713     2      3       1  16826680  16835520  16827398  16828074   
..   ...   ...    ...     ...       ...       ...       ...       ...   
495  791   245      2       1  27057907  27063778  27059066  27063391   
496  786   244      2       1  26425289  26425781  26425322  26425508   
497  786   243      2       1  26401908  26403656  26401908  26403656   
498   97   242      2       1  26076591  26098711  26077466  26098145   
499   97   241      2       1  26076591  26098052  26077221  26096529   

     exonCount                                         exonStarts  \
0            3                     [29836567, 29836912, 29837317]   
1           17  [28520664, 28521356, 28521541, 28521814, 28522...   
2           12  [28520664, 28521356, 28521541, 28522481, 28522...   
3            7  [16811698, 16822556, 16823102, 16823856, 16824...   
4            3                     [16826680, 16827675, 16834611]   
..         ...                                                ...   
495          8  [27057907, 27058712, 27059364, 27060257, 27060...   
496          2                               [26425289, 26425745]   
497          5  [26401908, 26402207, 26403003, 26403239, 26403...   
498         10  [26076591, 26078807, 26079366, 26079551, 26081...   
499         11  [26076591, 26077471, 26078807, 26079366, 26079...   

                                              exonEnds  score  name2  \
0                       [29836832, 29837262, 29837447]      0     42   
1    [28521298, 28521473, 28521700, 28522231, 28522...      0    264   
2    [28521298, 28521473, 28521700, 28522632, 28523...      0    264   
3    [16812061, 16822772, 16823206, 16824118, 16824...      0    159   
4                       [16827605, 16828075, 16835520]      0     29   
..                                                 ...    ...    ...   
495  [27058582, 27059119, 27060196, 27060540, 27061...      0    247   
496                               [26425520, 26425781]      0     96   
497  [26402137, 26402896, 26403184, 26403464, 26403...      0    343   
498  [26078682, 26078961, 26079473, 26079736, 26082...      0    314   
499  [26077235, 26078682, 26078961, 26079473, 26079...      0    314   

     cdsStartStat  csdEndStat  \
0               0           0   
1               0           0   
2               0           0   
3               0           0   
4               0           0   
..            ...         ...   
495             0           0   
496             0           0   
497             0           0   
498             0           0   
499             0           0   

                                            exonFrames  
0                                            [0, 0, 2]  
1    [1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2, 2, 0, ...  
2                 [1, 1, 1, 0, 1, 1, 0, 2, 2, 0, 2, 0]  
3                                [0, 2, 2, 1, 2, 2, 2]  
4                                           [0, 0, -1]  
..                                                 ...  
495                          [-1, 1, 0, 2, 1, 2, 1, 0]  
496                                            [0, -1]  
497                                    [2, 0, 2, 2, 0]  
498                     [2, 1, 2, 0, 0, 0, 1, 2, 1, 0]  
499                 [1, 2, 1, 2, 0, 0, 0, 1, 2, 0, -1]  

[500 rows x 16 columns]

In [45]:
max_length = df2['exonFrames'].apply(len).max()
df2['exonFrames'] = df2['exonFrames'].apply(lambda x: x + [0] * (max_length - len(x)))
max_length2 = df2['exonFrames'].apply(len).max()
df2['exonStarts'] = df2['exonStarts'].apply(lambda x: x + [0] * (max_length - len(x)))
max_length2 = df2['exonFrames'].apply(len).max()
df2['exonEnds'] = df2['exonEnds'].apply(lambda x: x + [0] * (max_length - len(x)))

In [46]:
d1=pd.DataFrame(df2['exonFrames'].tolist(), index=df.index) 
d2=pd.DataFrame(df2['exonStarts'].tolist(), index=df.index) 
d3=pd.DataFrame(df2['exonEnds'].tolist(), index=df.index) 


In [47]:
df2=pd.concat([df2,d1,d2,d3],axis=1)
df2=df2.drop(columns=["exonFrames","exonStarts","exonEnds"])

In [53]:
df2=df2.dropna(how="any",axis=0)
df2

In [58]:
df2.columns=[i for i,value in enumerate(df2.columns)]

In [60]:
df2

0      1    2    3           4           5           6           7    \
1    802.0  313.0  2.0  1.0  28520664.0  28540324.0  28521128.0  28539941.0   
4    713.0    2.0  3.0  1.0  16826680.0  16835520.0  16827398.0  16828074.0   
7     80.0   72.0  2.0  1.0   7858766.0   7886733.0   7858911.0   7885910.0   
8    646.0   73.0  2.0  0.0   8094123.0   8105083.0   8094148.0   8101808.0   
9    651.0   75.0  2.0  0.0   8773434.0   8773810.0   8773443.0   8773770.0   
..     ...    ...  ...  ...         ...         ...         ...         ...   
487  780.0  231.0  2.0  0.0  25680844.0  25683780.0  25680966.0  25683088.0   
488  780.0  230.0  2.0  0.0  25647245.0  25650250.0  25648898.0  25650047.0   
497  786.0  243.0  2.0  1.0  26401908.0  26403656.0  26401908.0  26403656.0   
498   97.0  242.0  2.0  1.0  26076591.0  26098711.0  26077466.0  26098145.0   
499   97.0  241.0  2.0  1.0  26076591.0  26098052.0  26077221.0  26096529.0   

      8    9    ...  108  109  110  111  112  113  114  115  116  117  
1    17.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     3.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7    15.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
8     5.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9     2.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
487   7.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
488   4.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
497   5.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
498  10.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
499  11.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[446 rows x 118 columns]

In [62]:
X2=df2.drop(columns=[3])
Y2=df2[3]


In [63]:
X_train2,X_test2,Y_train2,Y_test2=train_test_split(X2,Y2,test_size=0.2,random_state=42)

In [64]:
def model_train_classif(X_train,X_test,Y_train,Y_test):
    for i in [RandomForestClassifier(),GradientBoostingClassifier(),AdaBoostClassifier(),BaggingClassifier(),KNeighborsClassifier(),DecisionTreeClassifier()]:
        random_reg=i
        random_reg.fit(X_train,Y_train)
        print(f"The Accuracy score {i} is :",random_reg.score(X_test,Y_test))
model_train_classif(X_train2,X_test2,Y_train2,Y_test2)

The Accuracy score RandomForestClassifier() is : 0.6111111111111112
The Accuracy score GradientBoostingClassifier() is : 0.6444444444444445
The Accuracy score AdaBoostClassifier() is : 0.6111111111111112
The Accuracy score BaggingClassifier() is : 0.6
The Accuracy score KNeighborsClassifier() is : 0.4777777777777778
The Accuracy score DecisionTreeClassifier() is : 0.6


# # # data3

In [28]:
df3=pd.read_csv("/kaggle/input/drosophila-melanogaster-genome/ensembl-pep.csv")

In [29]:
label=df3["name"]
df3=df3.iloc[:5,-1]


In [30]:
df3

0    MAASDKSVDDSLYPIAVLIDELKNEDVQLRLNSIKKLSTIALALGE...
1    MFDLTGKHVCYVADCGGIALETSKVLMTKNIAKLAILQSTENPQAI...
2    MTRYKQTEFTEDDSSSIGGIQLNEATGHTGMQIRYHTARATWNWRS...
3    MTCTLVLLIASVLHFRMRGSCLLDIERFPVIPGTIYAGHIAYCAIL...
4    MDISKVDSTRALVNHWRIFRIMGIHPPGKRTFWGRHYTAYSMVWNV...
Name: seq, dtype: object

In [5]:
# df3[0]

name                                                seq
0  FBtr0005088.1  MAASDKSVDDSLYPIAVLIDELKNEDVQLRLNSIKKLSTIALALGE...
1  FBtr0006151.1  MFDLTGKHVCYVADCGGIALETSKVLMTKNIAKLAILQSTENPQAI...
2  FBtr0070000.1  MTRYKQTEFTEDDSSSIGGIQLNEATGHTGMQIRYHTARATWNWRS...
3  FBtr0070002.1  MTCTLVLLIASVLHFRMRGSCLLDIERFPVIPGTIYAGHIAYCAIL...
4  FBtr0070003.1  MDISKVDSTRALVNHWRIFRIMGIHPPGKRTFWGRHYTAYSMVWNV...

In [31]:
from transformers import BertTokenizer, BertModel

# Load ProtBERT (this is the tokenizer and model for protein sequences)
model_name = "Rostlab/prot_bert_bfd"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name)

# Example protein sequence
sequence = "MAASDKSVDDSLYPIAVLIDELK"

# Tokenize and get embeddings
inputs = tokenizer(sequence, return_tensors="pt")
outputs = model(**inputs)

# Get the embeddings (taking the last hidden state)
embeddings = outputs.last_hidden_state
print(f"Embeddings: {embeddings}")


Embeddings: tensor([[[ 0.0305,  0.0244,  0.1363,  ..., -0.0868, -0.1145, -0.0130],
         [ 0.0306,  0.0243,  0.1364,  ..., -0.0869, -0.1144, -0.0130],
         [ 0.0306,  0.0243,  0.1363,  ..., -0.0868, -0.1145, -0.0130]]],
       grad_fn=<NativeLayerNormBackward0>)


In [32]:
embeddings.shape

torch.Size([1, 3, 1024])

In [33]:
# df3["seq"]=df3["seq"].apply(lambda x:[tokenize(x,return_tensors="pt")])
# df3["seq"]=df2["seq"].apply(lambda x:[model(x)])

In [35]:
from transformers import BertTokenizer,BertModel

def bert_token(sequence):
    
    model_name = "Rostlab/prot_bert_bfd"
    tokenizer=BertTokenizer.from_pretrained(model_name)
    model=BertModel.from_pretrained(model_name)
    inputs=tokenizer(sequence,return_tensors="pt")
    encoded=model(**inputs)
    return encoded.last_hidden_state
d=df3.apply(lambda x:bert_token(x))

In [ ]:
de=d.apply(lambda x:x.flatten().detach().numpy())

In [ ]:
dfe=np.array(de)

In [38]:
dfe

array([array([ 0.03054758,  0.02437583,  0.13630426, ..., -0.08683145,
              -0.11449739, -0.01299063], dtype=float32)               ,
       array([ 0.03054758,  0.02437583,  0.13630426, ..., -0.08683145,
              -0.11449739, -0.01299063], dtype=float32)               ,
       array([ 0.03054758,  0.02437583,  0.13630426, ..., -0.08683145,
              -0.11449739, -0.01299063], dtype=float32)               ,
       array([ 0.03054758,  0.02437583,  0.13630426, ..., -0.08683145,
              -0.11449739, -0.01299063], dtype=float32)               ,
       array([ 0.03054758,  0.02437583,  0.13630426, ..., -0.08683145,
              -0.11449739, -0.01299063], dtype=float32)               ],
      dtype=object)

In [42]:
import tensorflow as tf
 tensor=tf.convert_to_tensor(de,dtype=tf.float32)

ValueError: setting an array element with a sequence.

In [37]:
# X_train3,X_test3,Y_train3,Y_test3=train_test_split(dfe,label,test_size=0.2,random_state=42)

In [ ]:
random_classif=RandomForestClassifier()
random_classif.fit(X_train,Y_train)
random_classif.score(X_test,Y_test)