In [78]:
!pip install pennylane tensorflow-quantum cirq

/opt/conda/lib/python3.10/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()


In [79]:
import pennylane as qml
import pandas as pd
import numpy as np
import cirq


In [80]:
import tensorflow_quantum as tfq

In [82]:
# df.dtypes,.sample(),.head(),.tail()
# plt.plot(df)
# plt.show()

# # # # Runned code

In [83]:
import tensorflow as tf
import tensorflow_quantum as tfq
import cirq
import sympy
import numpy as np

# Create a simple quantum circuit with a parameterized gate
qubit = cirq.GridQubit(0, 0)
theta = sympy.Symbol('theta')
circuit = cirq.Circuit(cirq.rx(theta)(qubit))

# Prepare a batch of circuits
num_samples = 5
circuit_batch = tfq.convert_to_tensor([circuit] * num_samples)

# Define the readout operator
readout_op = cirq.Z(qubit)
readout_op_batch = tfq.convert_to_tensor([[readout_op]] * num_samples)

# Create a TFQ Expectation layer
expectation_layer = tfq.layers.Expectation()

# Prepare input data: symbol values for theta
theta_values = np.array([[0.0], [np.pi / 2], [np.pi], [3 * np.pi / 2], [2 * np.pi]])
theta_tensor = tf.convert_to_tensor(theta_values, dtype=tf.float32)

# Calculate the expectation values
expectation_values = expectation_layer(
    circuit_batch, symbol_names=['theta'], symbol_values=theta_tensor, operators=readout_op_batch)

# Print the results
print("Theta values:\n", theta_values)
print("Expectation values:\n", expectation_values.numpy())

# Check if TFQ is working properly by comparing expected results
expected_values = np.cos(theta_values)
print("Expected values:\n", expected_values)
print("Difference:\n", np.abs(expectation_values.numpy() - expected_values))


Theta values:
 [[0.        ]
 [1.57079633]
 [3.14159265]
 [4.71238898]
 [6.28318531]]
Expectation values:
 [[ 1.0000000e+00]
 [-6.5565109e-07]
 [-1.0000000e+00]
 [ 1.4007092e-06]
 [ 1.0000000e+00]]
Expected values:
 [[ 1.0000000e+00]
 [ 6.1232340e-17]
 [-1.0000000e+00]
 [-1.8369702e-16]
 [ 1.0000000e+00]]
Difference:
 [[0.00000000e+00]
 [6.55651093e-07]
 [0.00000000e+00]
 [1.40070915e-06]
 [0.00000000e+00]]


In [84]:
import cirq 
import numpy as np
import tensorflow_quantum as tfq
from cirq.contrib.svg import SVGCircuit
from more_itertools import flatten

In [143]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import FunctionTransformer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

In [115]:
iris=load_iris()

In [118]:
X=iris.data
Y=iris.target

In [122]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [125]:
scaler=StandardScaler()
X_trains=scaler.fit_transform(X_train)
X_tests=scaler.transform(X_test)

In [131]:
def create_circuit(data):
    qubit=cirq.GridQubit.rect(1,len(data))
    for i,value in enumerate(qubit):
        circuit=cirq.Circuit([
            cirq.rx(value).on(qubit[i]),
            cirq.ry(value).on(qubit[i])
        ])
        return circuit

In [138]:
def simulate_circuit(data):
    features=[]
    simulate=cirq.Simulator()
    for d in data:
        circuit=create_cirucit(d)

        simul_run=simulate.simulate(cirucit)
        result=simul_run.final_state_vector
        state_vec=np.real(state_vec)
        features.append(state_vec)
        
    return np.array(features)

data_transform=FunctionTransformer()


In [144]:
pipe=Pipeline([
    ("quantum_circuit",data_transform),
    ("svm",SVC())
])


In [145]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('quantum_circuit', FunctionTransformer()), ('svm', SVC())])

In [146]:
predict=pipe.predict(X_test)

In [147]:
pipe.score(X_test,Y_test)

0.9473684210526315

In [148]:
pipe.score(X_train,Y_train)

0.9821428571428571